server:
  port: 8081
spring:
  application:
    name: eureka-provider-ticket
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/